apiVersion: apps/v1
kind: Deployment
metadata:
  name: authln-user-service
  labels:
    app: authln-user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authln-user-service
  template:
    metadata:
      labels:
        app: authln-user-service
    spec:
      containers:
        - name: authln-user-service
          image: authlnacr.azurecr.io/authln-user-service:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: KEY_VAULT_URL
              value: 'https://authln-keys-and-secrets.vault.azure.net'
          resources:
            limits:
              memory: '1Gi'
              cpu: '500m'
            requests:
              memory: '512Mi'
              cpu: '250m'
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
