apiVersion: apps/v1
kind: Deployment
metadata:
  name: authln-user-service
  namespace: authln
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authln-user-service
  template:
    metadata:
      labels:
        app: authln-user-service
    spec:
      containers:
        - name: authln-user-service
          image: ryanpaglioneauthln/authln-user-service:latest
          ports:
            - containerPort: 3000
