apiVersion: apps/v1
kind: Deployment
metadata:
  name: authln-user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authln-user-service
  template:
    metadata:
      labels:
        app: authln-user-service
    spec:
      containers:
        - name: authln-user-service
          image: ryanpaglioneauthln/authln-user-service:latest
          ports:
            - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: authln-user-service
spec:
  selector:
    app: authln-user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
