apiVersion: v1
kind: Service
metadata:
  name: authln-user-service
  namespace: authln
  labels:
    app: authln-user-service
spec:
  selector:
    app: authln-user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
