name: CI for AuthLN User Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Format code
      - name: Format code
        run: npm run format

      # Step 5: Type-check
      - name: TypeScript type-check
        run: npm run type-check

      # Step 6: Lint
      - name: Lint code
        run: npm run lint

      # Step 7: Run tests
      - name: Run tests
        run: npm test

      # Step 8: Build application
      - name: Build application
        run: npm run build
