name: CI for AuthLN User Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format

      - name: TypeScript type-check
        run: npm run type-check

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Fetch secrets from Azure Key Vault
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          export DB_HOST=$(az keyvault secret show --vault-name authln-keys-and-secrets --name DB-HOST --query value -o tsv)
          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV

      - name: Verify Secrets
        run: "echo 'DB_HOST: ${{ env.DB_HOST }}'"
